"""Add User

Revision ID: 791adf80bb17
Revises: 5a6a7bee4002
Create Date: 2026-02-20 14:23:42.309532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791adf80bb17'
down_revision = '5a6a7bee4002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comment')
    op.drop_table('todo_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('done', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=250), nullable=False),
    sa.Column('todo_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todo_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('todo')
    # ### end Alembic commands ###
